# Generated by Django 2.0.6 on 2019-06-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemessage',
            options={'verbose_name_plural': '通知'},
        ),
    ]
