# Generated by Django 2.0.6 on 2019-07-09 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extends', '0002_auto_20190601_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.IntegerField()),
                ('out_trade_no', models.CharField(max_length=100)),
                ('payjs_order_id', models.CharField(max_length=100)),
                ('type', models.CharField(default='wechatpay', max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('attach', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '支付',
                'ordering': ('-created',),
            },
        ),
    ]
