# Generated by Django 2.0.6 on 2019-07-09 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0020_articlespost_likes'),
        ('extends', '0004_auto_20190709_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_for_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='article.ArticlesPost', verbose_name='被赞赏文章'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
