# Generated by Django 2.0.6 on 2019-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extends', '0006_auto_20190711_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_for_article',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(default='wechat', max_length=100),
        ),
    ]
