# Generated by Django 2.0.6 on 2019-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20190212_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlespost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
