# Generated by Django 2.0.6 on 2019-07-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0003_auto_20190303_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
