# Generated by Django 2.0.6 on 2019-07-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20190303_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='total_likes',
            new_name='likes',
        ),
    ]
